version: '3.8'

services:

  backend:
    build:
      context: ./backend 
    container_name: nestjs-app
    ports:
      - "3000:3000" 
    depends_on:
      - redis 
    environment:
      - NODE_ENV=production
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
