version: '3.8'

networks:
  app-network:
    driver: bridge

services:

  backend:
    build:
      context: ./backend
    container_name: nestjs-app
    links:
      - redis
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - JWT_SECRET=0bee2b7d18252243ec707612a915fb621923c88e67204b9771bd78f4517471df30462bd8320895515f5358d82edac349c46253121ec6dc179d13feea3f1c3de9
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - app-network

volumes:
  redis-data: