version: '3.8'

networks:
  app-network:
    driver: bridge

services:

  backend:
    build:
      context: ./backend
    container_name: nestjs-app
    links:
      - redis
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - app-network

volumes:
  redis-data: