name: Build, Test, and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged
        ports:
          - 4000:4000
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker-compose -f docker-compose.yml build --no-cache backend

    - name: Tag Docker image
      run: docker tag $(docker images -q | head -n 1) ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest ${{ secrets.DOCKER_USERNAME }}/nestjs-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-app:${{ github.sha }}

    - name: Start Docker Compose services
      run: docker-compose up -d

    - name: Wait for the backend to be ready
      run: |
        echo "Waiting for the backend service to start..."
        RETRIES=5
        until curl -sSf http://localhost:4000/api || [ $RETRIES -eq 0 ]; do
          echo "Waiting for backend to be ready, retries left: $RETRIES..."
          sleep 10
          RETRIES=$((RETRIES-1))
        done
        if [ $RETRIES -eq 0 ]; then
          echo "Backend service failed to start."
          exit 1
        fi

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Tests
      run: newman run postman/api-tests.json

    - name: Trigger Render Deployment
      run: |
        curl -X POST -d '{}' ${{ secrets.RENDER_WEBHOOK_URL }}
